### ISSUE TITLE
Crashes if no detected_referrer_samples present

### ISSUE THREAD

**Issue by jordan-wright** [doomedraven/VirusTotalApi#16]
If I run the script using the ```-d -w -v``` options, there are some domains that do not return "detected_referrer_samples". This causes a KeyError to be thrown, crashing the script.

```
$ vt -d -w -v saxychiomzy.info
<snip>
Traceback (most recent call last):
  File "C:\Python27\Scripts\vt-script.py", line 9, in <module>
    load_entry_point('vt==1.0.7.2', 'console_scripts', 'vt')()
  File "C:\Python27\lib\site-packages\vt\vt.py", line 2087, in main
    options.subdomains, options.domain_siblings, options.categories, options.drweb_cat, options.alexa_cat, options.alexa_rank, options.opera_info)
  File "C:\Python27\lib\site-packages\vt\vt.py", line 1198, in getDomain
    undetected_referrer_samples
  File "C:\Python27\lib\site-packages\vt\vt.py", line 212, in print_results
    pretty_print(sorted(jdata['detected_referrer_samples']), [
KeyError: 'detected_referrer_samples'
```

**Comment by doomedraven** [comment]
@jordan-wright thank you for report it, patched, c&p mistake xD
now you can upgrade it from pip :)

best regards
