### ISSUE TITLE
Error didnt solve...

### ISSUE THREAD

**Issue by VikramKharvi** [doomedraven/VirusTotalApi#18]
vikram@vikram:~/VirusTotalApi/vt$ python vt.py -ur google.com virustotal.com
                                                       Traceback (most recent call last):
                                                       File "vt.py", line 3204, in <module>
                                                       main()
                                                       File "vt.py", line 3131, in main
                                                       vt.url_scan_and_report(**options)
                                                       File "vt.py", line 1719, in url_scan_and_report
                                                       url_upload = url_upload.strip()
                                                       AttributeError: 'list' object has no attribute 'strip'
Sorry sir the error still persist

**Comment by doomedraven** [comment]
thanks, this one is different from previous one, one day i should add unittests, going to fix it :)

**Comment by doomedraven** [comment]
pushed fix, let me know is that fix it
