### ISSUE TITLE
WindowsError: [Error 126] The specified module could not be found

### ISSUE THREAD

**Issue by SackOfHacks** [doomedraven/VirusTotalApi#25]
When I run vt.exe on windows 10, I get the following error:

Traceback (most recent call last):
  File "C:\Python27\Scripts\vt-script.py", line 11, in <module>
    load_entry_point('vt==3.0.0', 'console_scripts', 'vt')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2431, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\vt-3.0.0-py2.7.egg\vt\__main__.py", line 8, in <module>
    from .vt import main
  File "C:\Python27\lib\site-packages\vt-3.0.0-py2.7.egg\vt\vt.py", line 72, in <module>
    import magic
  File "C:\Python27\lib\site-packages\magic.py", line 159, in <module>
    libmagic = ctypes.CDLL(dll)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

So far I tried reinstalling the vt module, updating required modules and reinstalling python. Without success.

**Comment by doomedraven** [comment]
hello thanks for reporting but why `vt.exe` that doesn't exist, you should exec it as `python vt.py` i don't test a lot windows, well not test at all, bcz i don't use it

**Comment by doomedraven** [comment]
apart of that check if `magic` module is installed, bcz it looks like missed dependency

**Comment by SackOfHacks** [comment]
Thanks for responding doomdraven. 

vt.exe is created by setup.py when run on a windows system. 

I tested the python script with the same results:

C:\Python27\Scripts> python .\vt-script.py
Traceback (most recent call last):
  File ".\vt-script.py", line 11, in <module>
    load_entry_point('vt==3.0.0', 'console_scripts', 'vt')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2431, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\vt-3.0.0-py2.7.egg\vt\__main__.py", line 8, in <module>
    from .vt import main
  File "C:\Python27\lib\site-packages\vt-3.0.0-py2.7.egg\vt\vt.py", line 72, in <module>
    import magic
  File "C:\Python27\lib\site-packages\magic.py", line 159, in <module>
    libmagic = ctypes.CDLL(dll)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

You put me on the right track with the magic module dependency requirement. After I reinstalled the file-magic and python-magic modules the script now works.

Thanks and keep up the great work.

**Comment by doomedraven** [comment]
cool glad to hear that, closing al solved, feel free to reopen if needed
