### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by aogz** [doomedraven/VirusTotalApi#27]
I see some python3 related commits. Is module still incompatible with python3?

```
Collecting vt
  Downloading vt-3.1.3.3.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 591kB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/vt.egg-info
    writing pip-egg-info/vt.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f3/5tjmk_d56cs7s6v_0yfrl2n00000gn/T/pip-build-so9d0qi6/vt/setup.py", line 40, in <module>
        "six",
      File "/Users/mb/.virtualenvs/pr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/mb/.virtualenvs/pr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/Users/mb/.virtualenvs/pr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/Users/mb/.virtualenvs/pr/lib/python3.6/site-packages/setuptools/dist.py", line 67, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    TypeError: a bytes-like object is required, not 'str'
```

**Comment by doomedraven** [comment]
it looks like six dependency problem, gonna to fix it, thanks

**Comment by doomedraven** [comment]
can you provide please version of six in your system?
```
pip3 freeze | grep six
six==1.11.0
```

**Comment by aogz** [comment]
sure, six==1.11.0

**Comment by doomedraven** [comment]
thanks, i will check that after work

**Comment by aogz** [comment]
thanks, it would be great

**Comment by doomedraven** [comment]
fixed in pip, in git will push solution in a bit

**Comment by aogz** [comment]
awesome, thanks!

**Comment by doomedraven** [comment]
thanks for report it :)
