### ISSUE TITLE
get error "ValueError: zero length field name in format"

### ISSUE THREAD

**Issue by vus520** [doomedraven/VirusTotalApi#3]
``` python
python vt/vt.py -u https://dl.wandoujia.com/files/jupiter/latest/wandoujia-wandoujia_web.apk
Submitting url(s) for analysis:
    https://dl.wandoujia.com/files/jupiter/latest/wandoujia-wandoujia_web.apk
Traceback (most recent call last):
  File "vt/vt.py", line 3090, in <module>
    main()
  File "vt/vt.py", line 2999, in main
    vt.url_scan_and_report(**options)
  File "vt/vt.py", line 1702, in url_scan_and_report
    url = self.base.format('url/scan')
ValueError: zero length field name in format
```

all good on my mac with python 2.7
got this issue on centos 6 with python 2.6

**Comment by vus520** [comment]
fixed:

self.base = 'https://www.virustotal.com/vtapi/v2/{0}'

**Comment by doomedraven** [comment]
sorry didn't get the notification about this

**Comment by doomedraven** [comment]
weird behaviour, i will add 0 to base, thanks for report it :)
