### ISSUE TITLE
Problem with -si switch

### ISSUE THREAD

**Issue by KlausItem** [doomedraven/VirusTotalApi#38]
Hello,
if i querry a hash with the -s switch everything is ok, but if i use -si i got this error:

python vt.py -si 767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de
/home/internet/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "vt.py", line 3458, in <module>
    main()
  File "vt.py", line 3418, in main
    vt.getReport(**options)
  File "vt.py", line 643, in getReport
    if 'next' in jdata.get('data', dict).get('links', dict()) and kwargs.get('search_intelligence_limit', 1) > 1:
TypeError: descriptor 'get' requires a 'dict' object but received a 'str'

I do have a intelligence acount and set it up with the vtapi.conf

Please help.

**Comment by doomedraven** [comment]
Hello i will check in a bit your 2 issues

**Comment by doomedraven** [comment]
please test the fix, now it works fine, thanks again for reporting, don't hesitate to open new issues if you find any or reopen this one, to see all output in many function you need to specify specific arg or use `-v`

```
python vt.py -si 767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de -v
[+] Matched hash(es):
767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de - FS:2015-01-12 23:53:44 - LS:2019-04-27 20:10:27

[+] Basic


         Name                                                 Value
=========================================================================================================
                  size   88576
          authentihash   40cf9e20a70e31f22a5c0b92a3c58fbafceb662dd8762b477f0817915ba05d0a
                  sha1   8fef2c2bc87ef7d135296fdb4cf9ecd9c0322d55
                 magic   PE32 executable for MS Windows (console) Intel 80386 32-bit
                 vhash   0840876d15551c0d5d1d1038z2e02fz12z18fz
    last_analysis_date   2019-04-27 20:10:27
       meaningful_name   cmdow.exe
       times_submitted   236
  last_submission_date   2019-04-27 20:10:27
         creation_date   1.420e+09
        unique_sources   206
 first_submission_date   2015-01-12 23:53:44
      type_description   Win32 EXE
            reputation   116
last_modification_date   2019-04-28 16:55:28
              type_tag   peexe
                ssdeep   1536:ufVX5SG8cD++OTJ5enxjSiXkSxf5DqWtp0XU1jDBBrjK8o3agdbx583+fs7k+nUI:O5SG7S6/7k
                         +nUwoL1xii2l8NXQUQUlC
                sha256   767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de
           total_votes   {u'harmless': 11, u'malicious': 0}
                   md5   ddd12566b99343b96609afa2524ecec3

[+] Names
	 cmdow.exe
	f7e1cdd54cfbc736f3546ceda2b9b7b7-5769.exe
	/var/www/clean-mx/virusesevidence/output.114353461.txt
	%WINDIR%\cmdow.exe
	/var/www/clean-mx/virusesevidence/output.114178985.txt
	/var/www/clean-mx/virusesevidence/output.114136033.txt
	/var/www/clean-mx/virusesevidence/output.114028676.txt
	8bcf1da76fd37c0cd7440a947fc2fa3f-9646.exe
	%WINDIR%\1234567\cmdow.exe
	767b877e735c425b_cmdow.exe
	cmw.exe
	cmdow.exe"; filename*=utf-8' 'cmdow.exe
	2.exe
	C:\Users\Alex\Desktop\virus\2.exe
	cmdow.exe.quarantine
	T:\Downloads\cmdow.exe
	dca32f58-57c1-bd81-db04-82bac954ed34_1d297ebe0b4554b
	28f100fd-84bb-e42a-b15b-e56440bcb910_1d289f5627799f2
	CmdOW.Exe
	HZW1-02.exe
	2017.2.7-02.Trojan.Cmdow.exe%
	2017.2.7-02.Trojan.Cmdow.vir.HSvir
	767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de.bin
	Malware_MSEXE_767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de
	cmdow.jpg
	cmdow (1).exe
	fc202c64-4868-89c1-515e-314e95238b53_1d25d2b4b2e5156
	04e8c06c-ea29-5e23-9c41-023d81c37227_1d25c60e6574236
	283d7dd3-e0b6-6f00-da56-35d3f13d83d5_1d25ba91af580ff
	c08d4906-5924-39ad-ded1-47cc7d461895_1d241b783af48fc
	a79be139-5c35-4d18-cb9a-45adaed8f648_1d223ef3fbd8050
	887c276d-9168-eb54-33d5-f1428f404278_1d223cbf3913a31
	nith30se.frv
	ui1q2uer.bzm
	gtqdttoq.jip
	ibdwwz0o.uym
	yhqrxuzd.a3m
	ytnsf5xw.22o
	ysvdyclw.jtv
	zb3pq23w
	zb3pq23w.1rh
	b8619fe6-7590-d39b-811f-b8380fc5a96a_1d1f3083b727d65
	30104050-34ed-6103-df02-f2db1b6635f2_1d1f3057515dd0e
	92def650-514c-f607-c34c-d022adf7b065_1d1f240177c1ed8
	79f94343-a5bc-49f8-823b-36ab89e47ad8_1d1f23f8dcebd38
	wj1s2byz.tbr
	51bhqenw.s1b
	5b2tpf1f.p00
	3343ac01-6ef5-6254-5a77-5aa75f6a8730_1d1e806341b6140
	5nrlysd5.c3k
	cg300i3e.14m
	or3w3hdx.dr5
	k0vdssxl.dzx
	C:\Users\Vader\Desktop\samples\8fef2c2bc87ef7d135296fdb4cf9ecd9c0322d55
	99bab61a-7118-c512-1195-f143b0610cd9_1d1c1ad5788e5f3
	b19c1a5d-ae6f-05de-b260-94473a159fa6_1d1be5c7bba31b0
	870f9cab-d65a-c554-2294-5f9c3aed281c_1d1be5b91b26557
	3674e6ce-b5a4-26f5-3e90-a0f0a9e86510_1d1bc4012fbd037
	vzla.exe
	46101639-4a9b-0e9c-75bb-7e32ecfeddd7_1d1b820036caa83
	bite6d0.tmp
	biteffc.tmp
	CMDOW.EXE
	D:\Рабочий стол\cmdow.exe
	filename
	F:\DL\CMDOW\cmdow.exe
	C:\SEP\FalsePositive Files\cmdow.exe
	8c6b.tmp
	7780.tmp
	e51f201b.$$$
	avguihider.exe
	C:\programs\sys\shellext\cmdow.exe
	C:\Programs\sys\shellext\cmdow.exe
	C:\Users\s.vlems\Desktop\Security\dev\orchid\cmdow.exe
	C:\PATH\cmdow.exe
	d:\bt received files\diverse\bin\cmdow.exe
	C:\Windows\CMD\cmdow.exe
	C:\Users\Enno\Desktop\cmdow-1.4.8\bin\Release\cmdow.exe
	I:\laZagne\cmdow.exe
	c:\malware\2015-06-07-1761_sl\suspect_files_4_analysis\C_INTEL_GP_CMDOW.EXE_
	F:\util\cmdow.exe

[+] Tags
	 peexe
	via-tor

[+] Exiftool


          Name                                            Value
===============================================================================================
                MIMEType   application/octet-stream
               Subsystem   Windows command line
           LinkerVersion   2.220
             MachineType   Intel 386 or later, and compatibles
               TimeStamp   2014:12:30 12:08:55+01:00
ImageFileCharacteristics   No relocs, Executable, No line numbers, No symbols, 32-bit, No debug
                FileType   Win32 EXE
                  PEType   PE32
                CodeSize   58880
     InitializedDataSize   87552
              EntryPoint   0x1280
       FileTypeExtension   exe
        SubsystemVersion   4
            ImageVersion   1
               OSVersion   4
   UninitializedDataSize   19968

[+] Last analysis stats


      Name         Value
========================
      suspicious   0
        harmless   0
       malicious   17
      undetected   54
         failure   0
type-unsupported   1
         timeout   0


+-----------------------+------------------------------------------------------+----------------------+-------------+
|      Vendor name      |                        Result                        |       Version        | Last Update |
+=======================+======================================================+======================+=============+
|                  Bkav | None                                                 | 1.3.0.9899           |  20190425   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|           K7AntiVirus | None                                                 | 11.40.30732          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|          TotalDefense | None                                                 | 37.1.62.1            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|      MicroWorld-eScan | None                                                 | 14.0.297.0           |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                   CMC | None                                                 | 1.1.0.977            |  20190321   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|         CAT-QuickHeal | Trojan.AgentCS.S29823                                | 14                   |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 ALYac | None                                                 | 1.1.1.5              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|          Malwarebytes | None                                                 | 2.1.1.1115           |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                Zillya | None                                                 | 2.0.0.3804           |  20190426   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|           CrowdStrike | None                                                 | 1                    |  20190212   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Alibaba | RiskTool:Win32/CMDOW.596e1564                        | 0.4.0.6              |  20190426   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                  K7GW | None                                                 | 11.40.30732          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|            Cybereason | None                                                 |  --                  |  20180308   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|            TrendMicro | None                                                 | 10.0.0.1040          |  20190428   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 Baidu | None                                                 | 1.0.0.2              |  20190318   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|        NANO-Antivirus | Trojan.Win32.Cmdow.dmjuol                            | 1.0.134.24788        |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 Cyren | None                                                 | 6.2.0.1              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
| SymantecMobileInsight | None                                                 | 2                    |  20190418   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|            ESET-NOD32 | a variant of Win32/CMDOW.A potentially unsafe        | 19265                |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 Zoner | None                                                 | 1                    |  20190426   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             TheHacker | None                                                 | 6.8.0.5.4174         |  20190421   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 Avast | None                                                 | 18.4.3895.0          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                ClamAV | None                                                 | 0.101.2.0            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 GData | None                                                 | A:25.21698B:25.14948 |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             Kaspersky | not-a-virus:RiskTool.Win32.Cmdow.a                   | 15.0.1.13            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|           BitDefender | None                                                 | 7.200                |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Babable | None                                                 | 9107201              |  20190424   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               ViRobot | None                                                 | 2014.3.20.0          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|      SUPERAntiSpyware | None                                                 | 5.6.0.1032           |  20190423   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Tencent | Win32.Trojan.Gen.Qaql                                | 1.0.0.1              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Ad-Aware | None                                                 | 3.0.5.370            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             Trustlook | None                                                 | 1                    |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                Sophos | None                                                 | 4.98.0               |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                Comodo | ApplicUnwnt@#9l1z84ybav03                            | 30781                |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              F-Secure | None                                                 | 12.0.86.52           |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 DrWeb | None                                                 | 7.0.34.11020         |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 VIPRE | SecurityRisk.Cmdow (not malicious)                   | 74626                |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Invincea | None                                                 | 6.3.6.26157          |  20190313   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|     McAfee-GW-Edition | None                                                 | v2017.3010           |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Trapmine | None                                                 | 3.1.52.760           |  20190325   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               FireEye | None                                                 | 29.7.0.0             |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Emsisoft | None                                                 | 2018.4.0.1029        |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|           SentinelOne | None                                                 | 1.0.25.316           |  20190420   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                F-Prot | None                                                 | 4.7.1.166            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Endgame | None                                                 | 3.0.9                |  20190403   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Webroot | None                                                 | 1.0.0.403            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 Avira | None                                                 | 8.3.3.8              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               eGambit | Generic.Malware                                      | v4.3.6               |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             Antiy-AVL | Trojan/Win32.BTSGeneric                              | 3.0.0.1              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Kingsoft | None                                                 | 2013.8.14.323        |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             Microsoft | PUA:Win32/Presenoker                                 | 1.1.15900.4          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Jiangmin | RiskTool.Cmdow.a                                     | 16.0.100             |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Arcabit | None                                                 | 1.0.0.845            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              AegisLab | None                                                 | 4.200                |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             ZoneAlarm | not-a-virus:RiskTool.Win32.Cmdow.a                   | 1                    |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|          Avast-Mobile | None                                                 | 190427-00            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               TACHYON | None                                                 | 2019-04-27.02        |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             AhnLab-V3 | None                                                 | 3.15.0.23609         |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|               Acronis | None                                                 | 1.0.1.48             |  20190425   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                McAfee | None                                                 | 6.0.6.653            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                   MAX | None                                                 | 2018.9.12.1          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 VBA32 | None                                                 | 4.0.0                |  20190426   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                 Panda | None                                                 | 4.6.4.2              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|  TrendMicro-HouseCall | None                                                 | 10.0.0.1040          |  20190428   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                Rising | Trojan.Win32.Generic.17FDB432 (C64:YzY0Ohs14l4EXRZK) | 25.0.0.24            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                Yandex | Riskware.Agent!                                      | 5.5.1.3              |  20190426   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                Ikarus | PUA.CMDOW                                            | 0.1.5.2              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             MaxSecure | Trojan.Malware.7164915.susgen                        | 1.0.0.1              |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Fortinet | None                                                 | 5.4.247.0            |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|                   AVG | None                                                 | 18.4.3895.0          |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|              Paloalto | None                                                 | 1                    |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
|             Qihoo-360 | None                                                 | 1.0.0.1120           |  20190427   |
+-----------------------+------------------------------------------------------+----------------------+-------------+
```
