### ISSUE TITLE
Rescan fails with error in vt.py

### ISSUE THREAD

**Issue by rmenessec** [doomedraven/VirusTotalApi#5]
```
$ vt -r setup.exe 
Traceback (most recent call last):
  File "/usr/local/bin/vt", line 9, in <module>
    load_entry_point('vt==2.1.3.3', 'console_scripts', 'vt')()
  File "/usr/local/lib/python2.7/dist-packages/vt-2.1.3.3-py2.7.egg/vt/vt.py", line 3019, in main
    if options['date']:
KeyError: 'date'
```

Submitting files normally with -f appears to work fine.

**Comment by doomedraven** [comment]
@rmenessec thanks for reporting, update, now should work :)

**Comment by doomedraven** [comment]
@rmenessec closing, if you updated from github and still have issue let me know(reopen)
